// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"lqc.com/tree/app/model/internal"
)

// Postvote is the golang structure for table postvote.
type Postvote internal.Postvote

// Fill with you ideas below.
