// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"lqc.com/tree/app/model/internal"
)

// Postvote is the golang structure for table postvote.
type Postvote internal.Postvote

// Fill with you ideas below.

type PostvoteE struct {
	Postvote []*PostvoteE
}

type PostvoteDoVote struct {
	Userid int
	Pid    *int `json:"Pid" v:"required"`
	Vote   *int `json:"vote" v:"required|min:0|max:1"`
}
