// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"lqc.com/tree/app/model/internal"
)

// Post is the golang structure for table post.
type Post internal.Post

// Fill with you ideas below.
type PostE struct {
	*Post
	Replies  []*Reply    `json:"Replies"`
	Postvote []*Postvote `json:"Postvote"`
}

type PostDoCreate struct {
	Userid  int
	Title   string `json:"Title"  v:"required|length:6,30"`
	Content string `json:"Content" v:"required|length:10,255"`
}

type PostDoList struct {
	Page int `json:"page"   v:"required|integer|min:0"`
	Size int `json:"size"   v:"required|integer|min:1"`
}

type PostDoDelete struct {
	Pid *int `json:"pid"   v:"required|integer"`
}

type PostDoDetail struct {
	Pid *int `json:"pid"   v:"required|integer"`
}
