// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"lqc.com/tree/app/model/internal"
)

// Post is the golang structure for table post.
type Post internal.Post

// Fill with you ideas below.

type PostDoCreate struct {
	UserId  int
	Title   string
	Content string
}
