// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"lqc.com/tree/app/model/internal"
)

// Post is the golang structure for table post.
type Post internal.Post

// Fill with you ideas below.

type PostDoCreate struct {
	UserId  int
	Title   string `json:"Title"  v:"required|length:6,30"`    // 用户账号
	Content string `json:"Content" v:"required|length:10,255"` // 用户账号
}

type PostDoList struct {
	Page int `json:"page"   v:"required|integer|min:0"` // 用户账号
	Size int `json:"size"   v:"required|integer|min:1"` // 用户账号
}
