// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"lqc.com/tree/app/model/internal"
)

// Reply is the golang structure for table reply.
type Reply internal.Reply

// Fill with you ideas below.
