// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"lqc.com/tree/app/model/internal"
)

// Reply is the golang structure for table reply.
type Reply internal.Reply

type ReplyE struct {
	Replies   []*Reply
	Replyvote []*Replyvote
}

// Fill with you ideas below.

type ReplyDoCreate struct {
	Userid  int
	Pid     *int   `json:"pid"   v:"required|integer"`
	Content string `json:"Content" v:"required|length:10,255"`
}
