// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"lqc.com/tree/app/model/internal"
)

// Replyvote is the golang structure for table replyvote.
type Replyvote internal.Replyvote

type ReplyvoteE struct {
	Replyvote []*Replyvote
}

// Fill with you ideas below.
