// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Post is the golang structure for table post.
type Post struct {
	Id       uint        `orm:"id,primary" json:"id"`       //
	Userid   uint        `orm:"userid"     json:"userid"`   //
	CreateAt *gtime.Time `orm:"CreateAt"   json:"createAt"` //
	UpdateAt *gtime.Time `orm:"UpdateAt"   json:"updateAt"` //
	Title    string      `orm:"title"      json:"title"`    //
	Content  string      `orm:"content"    json:"content"`  //
	Deleted  int         `orm:"deleted"    json:"deleted"`  // 删除为1
	Status   int         `orm:"status"     json:"status"`   // 正常1,精华9
}
