// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Replyvote is the golang structure for table replyvote.
type Replyvote struct {
	Id       uint        `orm:"id,primary" json:"id"`       //
	Replyid  uint        `orm:"replyid"    json:"replyid"`  //
	Userid   uint        `orm:"userid"     json:"userid"`   //
	Vote     int         `orm:"vote"       json:"vote"`     // 点赞1,踩0
	CreateAt *gtime.Time `orm:"CreateAt"   json:"createAt"` //
}
