// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       uint        `orm:"id,primary" json:"id"`       //
	Passport string      `orm:"Passport"   json:"passport"` //
	Password string      `orm:"Password"   json:"password"` //
	Nickname string      `orm:"Nickname"   json:"nickname"` //
	CreateAt *gtime.Time `orm:"CreateAt"   json:"createAt"` //
	UpdateAt *gtime.Time `orm:"UpdateAt"   json:"updateAt"` //
	Status   int         `orm:"status"     json:"status"`   // 正常1,锁定2,拉黑-1,未激活0
}
