# HTTP Server.
[server]
address = ":80"
serverRoot = "public"
serverAgent = "gf-demos"
logPath = "/tmp/log/gf-demos/server"
nameToUriType = 2
SessionMaxAge = "10s"
graceful = true
# Cookie配置
cookieMaxAge = "365d"             # Cookie有效期。默认为365天
cookiePath = "/"                # Cookie有效路径。默认为"/"表示全站所有路径下有效
cookieDomain = ""                 # Cookie有效域名。默认为当前配置Cookie时的域名

# Sessions配置
sessionMaxAge = "10s"              # Session有效期。默认为24小时
sessionIdName = "sessionid"      # SessionId的键名名称。默认为gfsessionid
sessionCookieOutput = true               # Session特性开启时，是否将SessionId返回到Cookie中。默认true
sessionPath = "tmp/sessions"   # Session存储的文件目录路径。默认为当前系统临时目录下的gsessions目录
# Logger configurations.
[logger]
path = "/tmp/log/gf-demos"
level = "all"
stdout = true

# Template view configurations.
[viewer]
path = "template"
defaultFile = "index.html"

# Database configurations.
[database]
link = "mysql:root:12345678@tcp(192.168.0.105:3306)/test"
debug = true
# 数据库日志对象配置
[database.logger]
Path = "/tmp/log/gf-demos/sql"
Level = "all"
Stdout = true

# GF-CLI工具配置
[gfcli]
# 自定义DAO生成配置(默认是读取database配置)
[[gfcli.gen.dao]]
link = "mysql:root:123123@tcp(192.168.0.15:3306)/test"
tables = "user"

[redis]
default = "192.168.0.105:6379,0"
cache = "192.168.0.105:6379,1,123456?idleTimeout=600"