// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"lqc.com/tree/app/dao/internal"
)

// replyvoteDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type replyvoteDao struct {
	*internal.ReplyvoteDao
}

var (
	// Replyvote is globally public accessible object for table replyvote operations.
	Replyvote = &replyvoteDao{
		internal.Replyvote,
	}
)

// Fill with you ideas below.
